teams_17_18={'eng Premier League': ['Crystal Palace', 'Newcastle Utd', 'Swansea City', 'Stoke City',
        'West Ham', 'Bournemouth', 'Manchester City', 'Leicester City',
        'Tottenham', 'Liverpool', 'Chelsea', 'Watford', 'Burnley',
        'Arsenal', 'Southampton', 'Manchester Utd', 'Everton', 'Brighton',
        'West Brom', 'Huddersfield'], 
 'it Serie A': ['Hellas Verona', 'Milan', 'Sassuolo', 'Torino', 'Udinese',
        'Crotone', 'Lazio', 'Napoli', 'Roma', 'Sampdoria', 'Cagliari',
        'Benevento', 'SPAL', 'Juventus', 'Fiorentina', 'Bologna', 'Chievo',
        'Atalanta', 'Genoa', 'Inter'],
 'fr Ligue 1': ['Marseille', 'Dijon', 'Amiens', 'Paris S-G', 'Montpellier',
        'Strasbourg', 'Caen', 'Nantes', 'Lille', 'Rennes', 'Toulouse',
        'Angers', 'Lyon', 'Metz', 'Troyes', 'Monaco', 'Nice',
        'Saint-Etienne', 'Bordeaux', 'Guingamp'], 
 'es La Liga': ['Levante', 'Betis', 'Girona', 'Athletic Club', 'Alaves',
        'Real Sociedad', 'Las Palmas', 'Getafe', 'Barcelona', 'La Coruna',
        'Eibar', 'Leganes', 'Sevilla', 'Celta Vigo', 'Villarreal',
        'Real Madrid', 'Espanyol', 'Malaga', 'Valencia', 'Atletico Madrid'],
 'de Bundesliga': ['Eint Frankfurt', 'Freiburg', 'Mainz 05', 'Stuttgart', 'Dortmund',
        'Hoffenheim', 'Bayern Munich', 'Leverkusen', 'Hannover 96',
        'Hamburger SV', 'Wolfsburg', 'Augsburg', 'RB Leipzig',
        'Werder Bremen', 'Koln', "M'Gladbach", 'Schalke 04', 'Hertha BSC']}

teams_18_19={'fr Ligue 1': ['Strasbourg', 'Reims', 'Dijon', 'Saint-Etienne', 'Amiens',
        'Bordeaux', 'Montpellier', 'Monaco', 'Angers', 'Nimes', 'Nantes',
        'Paris S-G', 'Marseille', 'Toulouse', 'Rennes', 'Lyon', 'Lille',
        'Caen', 'Nice', 'Guingamp'], 
 'eng Premier League': ['Crystal Palace', 'Manchester City', 'Bournemouth',
        'Leicester City', 'Tottenham', 'Liverpool', 'Newcastle Utd',
        'Chelsea', 'West Ham', 'Brighton', 'Southampton', 'Cardiff City',
        'Arsenal', 'Fulham', 'Huddersfield', 'Manchester Utd', 'Everton',
        'Burnley', 'Wolves', 'Watford'],
 'it Serie A': ['Milan', 'Lazio', 'Empoli', 'Sassuolo', 'Atalanta', 'Udinese',
        'Torino', 'Napoli', 'Parma', 'Sampdoria', 'Cagliari', 'Chievo',
        'SPAL', 'Frosinone', 'Inter', 'Juventus', 'Fiorentina', 'Genoa',
        'Bologna', 'Roma'], 
 'de Bundesliga': ['Mainz 05', 'Eint Frankfurt', 'Freiburg', 'RB Leipzig',
        'Stuttgart', 'Dortmund', 'Hoffenheim', 'Hannover 96',
        'Bayern Munich', 'Leverkusen', 'Wolfsburg', 'Augsburg',
        'Werder Bremen', 'Dusseldorf', 'Nurnberg', "M'Gladbach",
        'Schalke 04', 'Hertha BSC'],
 'es La Liga': ['Atletico Madrid', 'Girona', 'Athletic Club', 'Rayo Vallecano',
        'Alaves', 'Huesca', 'Barcelona', 'Valladolid', 'Getafe', 'Leganes',
        'Celta Vigo', 'Eibar', 'Sevilla', 'Real Sociedad', 'Villarreal',
        'Real Madrid', 'Espanyol', 'Levante', 'Betis', 'Valencia']}

teams_19_20={'eng Premier League':['Crystal Palace', 'Norwich City', 'Chelsea', 'Southampton',
        'Liverpool', 'Manchester City', 'West Ham', 'Bournemouth',
        'Leicester City', 'Tottenham', 'Newcastle Utd', 'Brighton',
        'Arsenal', 'Manchester Utd', 'Everton', 'Sheffield Utd', 'Burnley',
        'Aston Villa', 'Wolves', 'Watford'], 
        'fr Ligue 1': ['Reims', 'Nantes', 'Saint-Etienne', 'Toulouse', 'Bordeaux',
        'Dijon', 'Monaco', 'Angers', 'Strasbourg', 'Marseille', 'Amiens',
        'Nimes', 'Metz', 'Lyon', 'Lille', 'Paris S-G', 'Nice', 'Brest',
        'Montpellier', 'Rennes'],
 'de Bundesliga': ['Union Berlin', 'Eint Frankfurt', 'Freiburg', 'RB Leipzig',
        'Hoffenheim', 'Dortmund', 'Bayern Munich', 'Leverkusen',
        'Dusseldorf', 'Paderborn 07', 'Wolfsburg', 'Hertha BSC',
        'Werder Bremen', 'Mainz 05', 'Koln', 'Augsburg', 'Schalke 04',
        "M'Gladbach"],
 'it Serie A': ['Lazio', 'Hellas Verona', 'Inter', 'Fiorentina', 'Genoa', 'Torino',
        'Brescia', 'Napoli', 'Parma', 'Roma', 'Atalanta', 'Sampdoria',
        'Lecce', 'Bologna', 'Udinese', 'Milan', 'Juventus', 'Sassuolo',
        'SPAL', 'Cagliari'], 
 'es La Liga': ['Atletico Madrid', 'Athletic Club', 'Mallorca', 'Alaves',
        'Celta Vigo', 'Barcelona', 'Villarreal', 'Valladolid', 'Betis',
        'Eibar', 'Leganes', 'Getafe', 'Real Sociedad', 'Real Madrid',
        'Osasuna', 'Granada', 'Sevilla', 'Levante', 'Espanyol', 'Valencia']}

teams_20_21={'fr Ligue 1': ['Strasbourg', 'Reims', 'Nantes', 'Lorient', 'Saint-Etienne',
        'Bordeaux', 'Rennes', 'Monaco', 'Nimes', 'Angers', 'Marseille',
        'Dijon', 'Metz', 'Lyon', 'Lille', 'Nice', 'Brest', 'Lens',
        'Paris S-G', 'Montpellier'],
 'eng Premier League': ['Crystal Palace', 'Chelsea', 'Southampton', 'Fulham', 'Liverpool',
        'Manchester City', 'Wolves', 'West Brom', 'Leicester City',
        'Tottenham', 'Arsenal', 'Leeds United', 'Everton', 'Newcastle Utd',
        'Brighton', 'Sheffield Utd', 'West Ham', 'Manchester Utd',
        'Burnley', 'Aston Villa'],
 'de Bundesliga': ['Mainz 05', 'Eint Frankfurt', 'Freiburg', 'RB Leipzig',
        'Hoffenheim', 'Werder Bremen', 'Stuttgart', 'Dortmund',
        'Bayern Munich', 'Leverkusen', 'Hertha BSC', 'Koln',
        'Union Berlin', 'Wolfsburg', 'Schalke 04', 'Arminia', 'Augsburg',
        "M'Gladbach"],
 'es La Liga': ['Getafe', 'Sevilla', 'Cadiz', 'Alaves', 'Celta Vigo', 'Betis',
        'Elche', 'Barcelona', 'Villarreal', 'Valladolid', 'Eibar',
        'Athletic Club', 'Granada', 'Real Sociedad', 'Real Madrid',
        'Osasuna', 'Levante', 'Valencia', 'Huesca', 'Atletico Madrid'],
 'it Serie A': ['Spezia', 'Lazio', 'Parma', 'Fiorentina', 'Udinese', 'Atalanta',
        'Hellas Verona', 'Torino', 'Bologna', 'Cagliari', 'Sampdoria',
        'Sassuolo', 'Genoa', 'Napoli', 'Benevento', 'Inter', 'Crotone',
        'Milan', 'Juventus', 'Roma']}


teams_21_22={'eng Premier League': ['Norwich City', 'Southampton', 'Wolves', 'Brentford',
        'Manchester City', 'Leicester City', 'Liverpool', 'Everton',
        'Tottenham', 'Newcastle Utd', 'Chelsea', 'Brighton',
        'Crystal Palace', 'West Ham', 'Aston Villa', 'Arsenal',
        'Leeds United', 'Watford', 'Manchester Utd', 'Burnley'],
       
 'fr Ligue 1': ['Reims', 'Clermont Foot', 'Lorient', 'Saint-Etienne', 'Rennes',
        'Nantes', 'Bordeaux', 'Brest', 'Monaco', 'Strasbourg', 'Metz',
        'Angers', 'Nice', 'Marseille', 'Lille', 'Lyon', 'Troyes', 'Lens',
        'Paris S-G', 'Montpellier'],
 'de Bundesliga': ['Greuther Furth', 'Eint Frankfurt', 'RB Leipzig', 'Hoffenheim',
        'Leverkusen', 'Stuttgart', 'Dortmund', 'Koln', 'Arminia',
        'Hertha BSC', 'Bochum', 'Wolfsburg', 'Union Berlin', 'Mainz 05',
        'Augsburg', "M'Gladbach", 'Bayern Munich', 'Freiburg'],
 'it Serie A': ['Roma', 'Lazio', 'Bologna', 'Spezia', 'Torino', 'Juventus',
        'Cagliari', 'Genoa', 'Venezia', 'Fiorentina', 'Udinese',
        'Sampdoria', 'Empoli', 'Salernitana', 'Sassuolo', 'Milan',
        'Hellas Verona', 'Inter', 'Atalanta', 'Napoli'],
 'es La Liga': ['Granada', 'Sevilla', 'Alaves', 'Athletic Club', 'Barcelona',
        'Rayo Vallecano', 'Celta Vigo', 'Cadiz', 'Betis', 'Real Madrid',
        'Villarreal', 'Valencia', 'Getafe', 'Mallorca', 'Osasuna', 'Elche',
        'Levante', 'Espanyol', 'Real Sociedad', 'Atletico Madrid']}

teams_22_23={'eng Premier League': ['Leeds United', 'Southampton', 'Fulham', 'West Ham',
        'Crystal Palace', 'Wolves', 'Brentford', 'Manchester City',
        'Leicester City', 'Liverpool', 'Everton', 'Newcastle Utd',
        'Bournemouth', 'Manchester Utd', 'Aston Villa', 'Chelsea',
        "Nott'ham Forest", 'Brighton', 'Tottenham', 'Arsenal'],
 'de Bundesliga': ['Eint Frankfurt', 'Koln', 'Dortmund', 'Leverkusen',
        'Werder Bremen', 'Stuttgart', 'Mainz 05', 'Hoffenheim',
        'Schalke 04', 'Wolfsburg', 'Bochum', 'Augsburg', 'Union Berlin',
        "M'Gladbach", 'RB Leipzig', 'Bayern Munich', 'Hertha BSC',
        'Freiburg'],
 'it Serie A': ['Udinese', 'Hellas Verona', 'Roma', 'Cremonese', 'Inter', 'Milan',
        'Bologna', 'Spezia', 'Torino', 'Empoli', 'Lazio', 'Sassuolo',
        'Sampdoria', 'Fiorentina', 'Monza', 'Lecce', 'Juventus', 'Napoli',
        'Atalanta', 'Salernitana'],
 'fr Ligue 1': ['Reims', 'Angers', 'Lens', 'Lorient', 'Auxerre', 'Rennes',
        'Toulouse', 'Nantes', 'Troyes', 'Monaco', 'Strasbourg',
        'Clermont Foot', 'Ajaccio', 'Nice', 'Lille', 'Lyon', 'Brest',
        'Marseille', 'Paris S-G', 'Montpellier'],
 'es La Liga': ['Betis', 'Valladolid', 'Sevilla', 'Athletic Club', 'Celta Vigo',
        'Almeria', 'Real Madrid', 'Barcelona', 'Cadiz', 'Villarreal',
        'Getafe', 'Elche', 'Real Sociedad', 'Valencia', 'Mallorca',
        'Girona', 'Osasuna', 'Rayo Vallecano', 'Espanyol',
        'Atletico Madrid']}

teams_23_24={'eng Premier League': ['Bournemouth', 'Sheffield Utd', 'Luton Town', 'Brighton',
        'West Ham', 'Crystal Palace', "Nott'ham Forest", 'Wolves',
        'Brentford', 'Manchester City', 'Liverpool', 'Newcastle Utd',
        'Burnley', 'Manchester Utd', 'Aston Villa', 'Fulham', 'Everton',
        'Tottenham', 'Chelsea', 'Arsenal'],
 'de Bundesliga': ['Union Berlin', 'Eint Frankfurt', 'Koln', 'Dortmund', 'Mainz 05',
        'Hoffenheim', 'Leverkusen', 'Stuttgart', 'Bochum', 'Wolfsburg',
        'Freiburg', 'Darmstadt 98', 'Augsburg', 'RB Leipzig', 'Heidenheim',
        'Werder Bremen', "M'Gladbach", 'Bayern Munich'],
 'fr Ligue 1': ['Reims', 'Lens', 'Lorient', 'Toulouse', 'Montpellier', 'Nantes',
        'Monaco', 'Le Havre', 'Clermont Foot', 'Lyon', 'Metz', 'Lille',
        'Paris S-G', 'Rennes', 'Nice', 'Marseille', 'Strasbourg', 'Brest'],
 'es La Liga': ['Betis', 'Alaves', 'Sevilla', 'Celta Vigo', 'Villarreal',
        'Almeria', 'Real Madrid', 'Cadiz', 'Getafe', 'Real Sociedad',
        'Valencia', 'Barcelona', 'Mallorca', 'Granada', 'Las Palmas',
        'Osasuna', 'Atletico Madrid', 'Rayo Vallecano', 'Athletic Club',
        'Girona'], 
 'it Serie A':['Bologna', 'Lazio', 'Lecce', 'Fiorentina', 'Roma', 'Inter',
        'Cagliari', 'Genoa', 'Frosinone', 'Sassuolo', 'Atalanta', 'Empoli',
        'Torino', 'Udinese', 'Monza', 'Salernitana', 'Hellas Verona',
        'Juventus', 'Napoli', 'Milan']}